### ISSUE TITLE
Installation fails, the package can't be found in PyPi

### ISSUE THREAD

**Issue by manuq** [endlessm/flapjack#3]
pip3 install fails with a 404 trying to fetch flapjack from PyPi. This is the verbose output:
```
$ pip3 install -vvv --user flapjack
Collecting flapjack
  1 location(s) to search for versions of flapjack:
  * https://pypi.python.org/simple/flapjack/
  Getting page https://pypi.python.org/simple/flapjack/
  Looking up "https://pypi.python.org/simple/flapjack/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/flapjack/ HTTP/1.1" 404 37
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/flapjack/: 404 Client Error: Not Found (flapjack does not exist) for url: https://pypi.python.org/simple/flapjack/ - skipping
  Could not find a version that satisfies the requirement flapjack (from versions: )
Cleaning up...
No matching distribution found for flapjack
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 346, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for flapjack
```

**Comment by manuq** [comment]
For now what works is clone this repository, then inside the cloned directory:
```
./setup.py build
./setup.py install --user
```

**Comment by ptomato** [comment]
Good point. I think I meant to do this at one point, then realized I needed to check if we had an Endless PyPI account, then forgot about it.

If you are using EndlessOS then flapjack is already installed, however it's an older version of 0.0.0 and the config file format isn't compatible. I'll try to make sure that flapjack 0.0.1 is released with EOS 3.3.4 next week.

**Comment by ptomato** [comment]
I uploaded the package to PyPI with my personal account for now.

**Comment by manuq** [comment]
Great! But even better is knowing that the current version of flapjack will work in Endless OS very soon!
