### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by mcatanzaro** [endlessm/flapjack#9]
I see the following error when running 'flapjack build':

```
$ flapjack build
Traceback (most recent call last):
  File "/home/mcatanzaro/.local/bin/flapjack", line 11, in <module>
    sys.exit(main())
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/main.py", line 32, in main
    sys.exit(command.run(args.options))
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/commands.py", line 63, in run
    return self.execute(args)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/commands.py", line 101, in execute
    exitcode = ext.flatpak_builder('--require-changes', '--repo', _REPO)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/ext.py", line 158, in flatpak_builder
    manifest = _generate_manifest()
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/ext.py", line 100, in _generate_manifest
    config_opts = config.module_extra_config_opts(m['name'])
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/config.py", line 78, in __call__
    return self.op(module, self.key, fallback=None)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/config.py", line 53, in _ws_sep_list
    return _config.get(*args, **kw).split()
AttributeError: 'NoneType' object has no attribute 'split'
```

I see it's related to my config. I have the following config file `~/.flapjack.ini`:

```
[Common]
workdir = ~/Projects/flapjack
modules = WebKitGTK+

[WebKitGTK+]
url = git://git.webkit.org/WebKit.git
```

It works if I change `_ws_sep_list` to not crash if `_config.get` returns `None`:

```
# config.py
def _ws_sep_list(*args, **kw):
    val = _config.get(*args, **kw)
    if val is not None:
        return val.split()
    return val
```

I don't know if that's the right fix, though. I don't actually understand the config code.

**Comment by mcatanzaro** [comment]
...aaaand going to make a pull request, I noticed you just made exactly that change yesterday. Should have checked that first I guess. Closing....

**Comment by mcatanzaro** [comment]
Hmmm, but now, after locally making the modification above to make `flapjack build` work, I see that `flapjack run` does not work either:

```
$ flapjack run org.gnome.Epiphany
613f6503ea403a520ec3d8bd9493051b7431e0dcff7468d08fda27d45a5a6285
Looking for updates...
e74c6ba25e74e86617979313d797dbeff4cb6e7c7c7638f72f5a30225f4fa4c5
Looking for updates...
Traceback (most recent call last):
  File "/usr/lib64/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib64/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib64/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'shell_permissions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mcatanzaro/.local/bin/flapjack", line 11, in <module>
    sys.exit(main())
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/main.py", line 32, in main
    sys.exit(command.run(args.options))
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/commands.py", line 63, in run
    return self.execute(args)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/commands.py", line 179, in execute
    args.app] +
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/config.py", line 42, in __call__
    return self.op('Common', self.key)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/flapjack/config.py", line 53, in _ws_sep_list
    val = _config.get(*args, **kw)
  File "/usr/lib64/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'shell_permissions' in section: 'Common'
```

I modified my config file to add `shell_permissions`:

```
[Common]
workdir = ~/Projects/flapjack
modules = WebKitGTK+

test_permissions =
    --socket=x11
    --socket=wayland

shell_permissions = ${test_permissions}
    --allow=devel
    --filesystem=home

[WebKitGTK+]
url = git://git.webkit.org/WebKit.git
```

Now it works. The config parser should surely be more robust, so reopening.
